### ISSUE TITLE
Nginx Container Fails to Start in Docker Compose Setup

### ISSUE THREAD

**Issue by acirtautas** [Sylius/Sylius-Standard#1116]
When initializing the Sylius development environment using the provided Docker Compose configuration, the nginx container fails to start automatically. This requires manual intervention to get the web server running.

**Steps to Reproduce:**
1. Clone a fresh Sylius project
3. Run `make init`
4. Run `make up`
5. Check container statuses

**Expected Behavior:**
Mysql, php and nginx containers up and running.

**Actual Behavior:**
The nginx container fails to start while other containers (php, mysql) are up.

**Workaround:**
Manually starting the nginx container.

**Proposed Solution:**
Add a dependency condition in the default `compose.override.dist.yml` file:
```yaml
nginx:
    # existing configuration...
    depends_on:
        php:
            condition: service_started
```

This ensures that nginx starts only after the PHP service is fully initialized, which resolves the startup issue.
