### ISSUE TITLE
[DX] Disable disable_delivery

### ISSUE THREAD

**Issue by bpolaszek** [Sylius/Sylius-Standard#221]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Sylius version   | 1.1

Hello there,

I'd like to suggest a DX improvement regarding transactionnal e-mails.

Today, when you install Sylius and run it in a `dev` environment, when you go to your shop and try to create an account, your shop sends you an email asking you to confirm your account.

The problem is that e-mail never comes, because of this:

```yaml
# app/config/config_dev.yml
swiftmailer:
    disable_delivery: true
```

If you logout and then try to login again, Sylius will throw the following error and you won't be able to login again:
> This account is disabled.

I obviously understand the need to not send e-mails for real in development environment. 
However, SwiftMailer has another great feature, that allows to route all outbound e-mails to one or several addresses:

```yaml
# app/config/config_dev.yml
swiftmailer:
    #disable_delivery: true
    delivery_addresses: ['bpolaszek@sylius.com'] # *wink*
```

I think that running `bin/console sylius/install` in development environment should ask a new parameter or env parameter, like `%env(ROUTE_ALL_EMAILS_TO)%` and `config_dev.yml` having this default configuration:

```yaml
# app/config/config_dev.yml
swiftmailer:
    #disable_delivery: true
    delivery_addresses: ['%env(ROUTE_ALL_EMAILS_TO)%'] # Maybe find a better name for this variable
```

Then, the cookbook could explain how to switch from a default e-mail address to disabling delivery (when it comes to testing a bigger shop, for instance), and how to allow Sylius to send emails for real.

What's your opinion?
