### ISSUE TITLE
install sylius with docker

### ISSUE THREAD

**Issue by hichamcave** [Sylius/Sylius-Standard#337]
I want to use sylius with docker

I followed the same steps of official website;

when I type the command "docker-compose pull --ignore-pull-failures || true", a have this error :

Pulling mysql   ... done
Pulling php     ... error
Pulling nodejs  ... error
Pulling nginx   ... error
Pulling mailhog ... done

ERROR: for nginx  unauthorized: access to the requested resource is not authorized

ERROR: for nodejs  unauthorized: access to the requested resource is not authorized

ERROR: for php  unauthorized: access to the requested resource is not authorized
ERROR: unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized

**Comment by gabiudrescu** [comment]
cannot reproduce anymore. managed to install Sylius with this docker setup without any problems.  @hichamcave can you confirm you still have this issue?

**Comment by mrkonovalov** [comment]
@gabiudrescu I had this problem 22.06.2009

MacOS last

**Comment by anthonymartin** [comment]
I also have this same problem. MacOS 10.13.6

**Comment by vasilvestre** [comment]
Tested and work at 1.5 and master

**Comment by jorgeriv** [comment]
I'm having the exact same problem with my linux machine. The funny thing is that I was able to install in my MacOS without any issue, sadly I need this to work in the linux machine =(

**Comment by gabiudrescu** [comment]
what is the exact command sequence you are running?

**Comment by bhupesh** [comment]
I am getting same error. Here are the sequence of commands that I ran.
`git clone https://github.com/Sylius/Sylius-Standard.git`
`cd Sylius-Standard\`
`docker-compose.exe --version`
`docker-compose pull --ignore-pull-failures || true`

Going to quay.io/sylius in browser gives 404 error.

**Comment by a-vasyliev** [comment]
Getting the same error here:
`docker-compose pull --ignore-pull-failures || true`

I've run `docker login` and was successfully authorized. Pull command is not working anyway... Any suggestions?

**Comment by a-vasyliev** [comment]
docker-compose version 1.25.4, build 8d51620a
macOS Catalina 10.15.3 (19D76)

**Comment by a-vasyliev** [comment]
I've found that I need to have an account on quay.io. I've created an account and have logged in successfully `docker login quay.io`. It doesn't help.

**Comment by cdarken** [comment]
Same here, I succeeded in pulling the images once, then I got the unauthorized errors on my production server. Now I can't pull even on my dev machine.

**Comment by deansoffer** [comment]
I've got the same error (win 10)

ERROR: for nginx  unauthorized: access to the requested resource is not authorized
ERROR: for nodejs  unauthorized: access to the requested resource is not authorized

**Comment by GregoireHebert** [comment]
Hi @lchrusciel, it seems that the images are not available in Quai.io anymore.
Could you check ?

**Comment by GregoireHebert** [comment]
oh I pinged Łukasz but I should have pinged @pamil ^^

**Comment by prodigeris** [comment]
Same issues.

**Comment by heyalexej** [comment]
Issue still exists.
Created an account on quay.io but the sylius namespace doesn't exist.

```
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F203

$ docker login quay.io
Authenticating with existing credentials...
Login Succeeded

$ docker-compose pull --ignore-pull-failures || true
Pulling mysql   ... done
Pulling php     ... error
Pulling nodejs  ... error
Pulling nginx   ... error
Pulling mailhog ... done

ERROR: for php  unauthorized: access to the requested resource is not authorized

ERROR: for nginx  unauthorized: access to the requested resource is not authorized

ERROR: for nodejs  unauthorized: access to the requested resource is not authorized
ERROR: unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized
unauthorized: access to the requested resource is not authorized
```

**Comment by Moxxie** [comment]
I found the following to work:

`git clone https://github.com/Sylius/Sylius-Standard.git`
`cd Sylius-Standard`
`docker-compose --version`
`docker-compose pull --ignore-pull-failures || true` (Ignore that it fails to pull :) )
`docker-compose build --pull`
`docker-compose up -d`
`docker-compose exec php bin/console sylius:install`
open http://localhost/

Hope this helps!

**Comment by joostvanmeeuwen** [comment]
I've the same problem. I am logged in via `docker login`
Error message: 
`Pulling php (quay.io/sylius/php:latest)...
ERROR: unauthorized: access to the requested resource is not authorized
`

**Comment by chiqui3d** [comment]
We got off to a good start with Sylius. It's not working for me. Same mistake as everyone else.

**Comment by aario** [comment]
Same here. Seems like an abandoned issue...

**Comment by deansoffer** [comment]
Modifying my docker-compose.yml to this worked for me:
still had some error afterwards, but at least i could build the image...

```
version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_php
    
    image: php:latest
    depends_on:
      - mysql
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://sylius:nopassword@mysql/sylius
      - MAILER_URL=smtp://mailhog:1025
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - .:/srv/sylius:rw,cached
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./var:/srv/sylius/var:rw
      - ./public:/srv/sylius/public:rw,delegated
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/sylius/public/media:rw
      - public-media:/srv/sylius/public/media:rw

  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=sylius
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"

  nodejs:
    build:
      context: .
      target: sylius_nodejs
    
    image: node:latest
    depends_on:
      - php
    environment:
      - GULP_ENV=dev
      - PHP_HOST=php
      - PHP_PORT=9000
    volumes:
      - .:/srv/sylius:rw,cached
      - ./public:/srv/sylius/public:rw,delegated
    ports:
      - "35729:35729"

  nginx:
    build:
      context: .
      target: sylius_nginx
    image: nginx:latest
    depends_on:
      - php
      - nodejs # to ensure correct build order
    volumes:
      - ./public:/srv/sylius/public:ro
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/sylius/public/media:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    ports:
      - "80:80"

  mailhog:
    # do not use in production!
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    # volumes:
    #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    ports:
      - "8025:8025"

volumes:
  mysql-data:
  public-media:

```

**Comment by Darkweak** [comment]
It seems this error came back on current installation @pamil could you re-up images on quay.io please.

Thanks

**Comment by nopenopenope** [comment]
I had to make some modifications, and instead of using percona, I swapped over to mariadb. My docker-compose file:

```
version: '3.4'

services:
    php:
        build:
            context: .
            target: sylius_php
        image: php:latest
        depends_on:
            - mysql
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - APP_SECRET=EDITME
            - DATABASE_URL=mysql://sylius:sylius@mysql/sylius?serverVersion=mariadb-10.3.11
            - MAILER_URL=smtp://mailhog:1025
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        volumes:
            - .:/srv/sylius
            - ./public:/srv/sylius/public
            - ./public/media:/srv/sylius/public/media

    mysql:
        image: mariadb:latest
        volumes:
            - ./docker/db/:/var/lib/mysql/
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: sylius
            MYSQL_DATABASE: sylius
            MYSQL_USER: sylius
            MYSQL_PASSWORD: sylius

    nodejs:
        build:
            context: .
            target: sylius_nodejs

        image: node:latest
        depends_on:
            - php
        environment:
            - GULP_ENV=dev
            - PHP_HOST=php
            - PHP_PORT=9000
        volumes:
            - .:/srv/sylius:rw
            - ./public:/srv/sylius/public
        ports:
            - "35729:35729"

    nginx:
        build:
            context: .
            target: sylius_nginx
        image: nginx:latest
        depends_on:
            - php
            - nodejs # to ensure correct build order
        volumes:
            - ./public:/srv/sylius/public
            - ./public/media:/srv/sylius/public/media
        ports:
            - "80:80"

    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
            - MH_STORAGE=maildir
        # volumes:
        #   - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
            - "8025:8025"

```

Worth saying that I use Ubuntu for development. The bindings for PHP seem redundant... I don't think we need that level of recursion on adding volumes when binding via Docker-compose, the first line is enough I believe.
