### ISSUE TITLE
Sylius does not autoload configuration files when having them presented in Bundles

### ISSUE THREAD

**Issue by nopenopenope** [Sylius/Sylius-Standard#478]
Hi everyone, great job maintaining the framework, really a good job!

I am using the Sylius-1.9.0 DEV version. 

I generated a new Sylius Plugin and am trying to create a new Sonata Sylius_ui configuration:
```
// Resources/config/app/config.yml
imports:
    - { resource: "@SyliusUiBundle/Resources/config/app/config.yml" }
    
sonata_block:
    default_contexts: ~
    
sylius_ui:
    events:
        my.framework.settings:
            blocks:
                content:
                    template: "@MySyliusThemePlugin/Framework/Components/_test.twig"

```
However, the Core method only loads a whitelisted subset of config files. This means that developers have to add them similar to the code in SyliusCoreExtension::prependSyliusThemeBundle(). Whilst I didn't found the respective mechanism being documented (or at least didn't found hints regarding it in the Docs).

I haven't Xdebug getting running yet, but I think all available extensions should be mapped to the config automatically to ease the development and make the structure less complex, but I am also happy to hear any "simple" or convenient way to automatically include my bundles app/config.yml files to the sonata logic.
