### ISSUE TITLE
Changing bundle structure of sylius-standard

### ISSUE THREAD

**Issue by madc** [Sylius/Sylius-Standard#56]
I've just been setting up a new project and wanted to use some of the features of the current 0.13 branch. Now sylius-standard is kind of outdated and the search is not working out of the box. Also i find it kind of strange, that the sylius-standard just has a dependency on the sylius repo, not the individual components. But on the other hand, the sylius repo is not upgradeable via composer.

To solve this, i just checked out the sylius repo, deleted the `src/Sylius` folder and updated the `composer.json` as seen below. I think, it would be great, if the sylius-standard edition would be handled similar in the future. This has quite some advantages as the configuration stays in `app/config` and the structure is easier to understand.

```yml
{
    "name":        "sylius/sylius",
    "type":        "project",
    "description": "Modern ecommerce for Symfony2",
    "license":     "MIT",
    "homepage":    "http://sylius.org",
    "authors": [
        {
            "name":     "Paweł Jędrzejewski",
            "homepage": "http://pjedrzejewski.com"
        },
        {
            "name":     "Sylius project",
            "homepage": "http://sylius.org"
        },
        {
            "name":     "Community contributions",
            "homepage": "http://github.com/Sylius/Sylius/contributors"
        }
    ],
    "repositories": [
        {
            "type":     "vcs",
            "url":      "https://github.com/Sylius/SyliusArchetypeBundle"
        },
        {
            "type":     "vcs",
            "url":      "https://github.com/Sylius/Archetype"
        }
    ],
    "require": {
        "php":                                  ">=5.3.3",
        "a2lix/translation-form-bundle":        "~2.0",
        "doctrine/collections":                 "~1.2",
        "doctrine/common":                      "~2.3",
        "doctrine/doctrine-bundle":             "~1.3",
        "doctrine/doctrine-cache-bundle":       "~1.0",
        "doctrine/doctrine-migrations-bundle":  "2.1.*@dev",
        "doctrine/migrations":                  "~1.0@dev",
        "doctrine/orm":                         "~2.4",
        "friendsofsymfony/elastica-bundle":     "^3.0.2",
        "friendsofsymfony/oauth-server-bundle": "~1.4",
        "friendsofsymfony/rest-bundle":         "~1.5",
        "friendsofsymfony/user-bundle":         "2.0.*@dev",
        "hwi/oauth-bundle":                     "~0.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "jackalope/jackalope":                  "^1.1.4",
        "jackalope/jackalope-doctrine-dbal":    "^1.1.2",
        "jms/serializer-bundle":                "~0.13",
        "jms/translation-bundle":               "~1.1",
        "knplabs/gaufrette":                    "0.2.*@dev",
        "knplabs/knp-gaufrette-bundle":         "0.2.*@dev",
        "knplabs/knp-menu-bundle":              "~1.1",
        "knplabs/knp-snappy-bundle":            "*@dev",
        "liip/imagine-bundle":                  "~1.0",
        "mathiasverraes/money":                 "*@dev",
        "omnipay/omnipay":                      "~2.3",
        "payum/payum":                          "0.12.*",
        "payum/payum-bundle":                   "0.12.*",
        "sensio/distribution-bundle":           "~2.3",
        "stof/doctrine-extensions-bundle":      "~1.1",
        "swiftmailer/swiftmailer":              "~5.0",
        "symfony/assetic-bundle":               "~2.3",
        "symfony/event-dispatcher":             "~2.3",
        "symfony/expression-language":          "~2.4",
        "symfony/form":                         "~2.3",
        "symfony/framework-bundle":             "~2.3",
        "symfony/intl":                         "~2.3",
        "symfony/monolog-bundle":               "~2.3",
        "symfony/options-resolver":             "~2.3",
        "symfony/property-access":              "~2.3",
        "symfony/swiftmailer-bundle":           "~2.3",
        "symfony/symfony":                      "~2.3",
        "symfony/twig-bundle":                  "~2.3",
        "twig/extensions":                      "~1.0",
        "twig/twig":                            "~1.11",
        "white-october/pagerfanta-bundle":      "~1.0",
        "willdurand/hateoas-bundle":            "@stable",
        "winzou/state-machine":                 "~0.1",
        "winzou/state-machine-bundle":          "~0.2",
        "payum/omnipay-bridge":                 "~0.12",
		
	"sylius/addressing-bundle": "0.13.*@dev",
	"sylius/archetype-bundle": "0.13.*@dev",
	"sylius/api-bundle": "0.13.*@dev",
	"sylius/archetype-bundle":  "0.13.*@dev",
	"sylius/attribute-bundle": "0.13.*@dev",
	"sylius/cart-bundle": "0.13.*@dev",
	"sylius/core-bundle": "0.13.*@dev",
	"sylius/contact-bundle": "0.13.*@dev",
	"sylius/content-bundle": "0.13.*@dev",
	"sylius/currency-bundle": "0.13.*@dev",
        "sylius/fixtures-bundle": "0.13.*@dev",
        "sylius/flow-bundle": "0.13.*@dev",
        "sylius/installer-bundle": "0.13.*@dev",
        "sylius/inventory-bundle": "0.13.*@dev",
        "sylius/locale-bundle": "0.13.*@dev",
        "sylius/money-bundle": "0.13.*@dev",
        "sylius/order-bundle": "0.13.*@dev",
        "sylius/payment-bundle": "0.13.*@dev",
        "sylius/payum-bundle": "0.13.*@dev",
        "sylius/pricing-bundle": "0.13.*@dev",
        "sylius/product-bundle": "0.13.*@dev",
        "sylius/promotion-bundle": "0.13.*@dev",
        "sylius/resource-bundle": "0.13.*@dev",
        "sylius/search-bundle": "0.13.*@dev",
        "sylius/sequence-bundle": "0.13.*@dev",
        "sylius/settings-bundle": "0.13.*@dev",
        "sylius/shipping-bundle": "0.13.*@dev",
        "sylius/taxation-bundle": "0.13.*@dev",
        "sylius/taxonomy-bundle": "0.13.*@dev",
        "sylius/translation-bundle": "0.13.*@dev",
        "sylius/variation-bundle": "0.13.*@dev",
        "sylius/web-bundle": "0.13.*@dev",
		
        "sylius/addressing": "0.13.*@dev",
		"sylius/archetype": "0.13.*@dev",
        "sylius/attribute": "0.13.*@dev",
        "sylius/cart": "0.13.*@dev",
        "sylius/contact": "0.13.*@dev",
        "sylius/core": "0.13.*@dev",
        "sylius/currency": "0.13.*@dev",
        "sylius/inventory": "0.13.*@dev",
        "sylius/locale": "0.13.*@dev",
        "sylius/payment": "0.13.*@dev",
        "sylius/pricing": "0.13.*@dev",
        "sylius/product": "0.13.*@dev",
        "sylius/promotion": "0.13.*@dev",
        "sylius/registry": "0.13.*@dev",
        "sylius/resource": "0.13.*@dev",
        "sylius/sequence": "0.13.*@dev",
        "sylius/shipping": "0.13.*@dev",
        "sylius/storage": "0.13.*@dev",
        "sylius/taxation": "0.13.*@dev",
        "sylius/taxonomy": "0.13.*@dev",
        "sylius/translation": "0.13.*@dev",
        "sylius/variation": "0.13.*@dev",
		"sylius/order": "0.13.*@dev",
		"sylius/originator": "0.13.*@dev"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "~2.2",
        "behat/behat":                       "~3.0",
        "behat/symfony2-extension":          "~2.0",
        "behat/mink-extension":              "~2.0",
        "behat/mink-browserkit-driver":      "~1.2",
        "behat/mink-selenium2-driver":       "~1.2",
        "behat/mink":                        "~1.6",
        "coduo/php-matcher":                 "~1.0",
        "fzaninotto/faker":                  "~1.2",
        "phpspec/phpspec":                   "~2.1",
        "phpunit/phpunit":                   "~4.1"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.13-dev"
        },
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```
