### ISSUE TITLE
Media directory permissions problem using Docker (Sylius 1.12.1)

### ISSUE THREAD

**Issue by valentin-harrang** [Sylius/Sylius-Standard#893]
**Sylius version affected**: 1.12.1

**Description**  

I just installed Sylius `1.12.1` via Docker (following the documentation) and when I want to upload an image to a product from the admin panel, I get this permissions error:

`2022/12/16 13:26:12 [crit] 32#32: *843 stat() "/srv/sylius/public/media/cache/sylius_small/50/09/d7acd0e47c4b6c598e5fd25fd206.jpg" failed (13: Permission denied), client: 172.18.0.1, server: , request: "GET /media/cache/sylius_small/50/09/d7acd0e47c4b6c598e5fd25fd206.jpg HTTP/1.1", host: "localhost", referrer: "http://localhost/admin/products/22/edit"`

However, there are these lines in the `docker/php/docker-entrypoint.sh` file which is supposed to define the rights on the `public/media` folder : 

```
setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var public/media
setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var public/media
```

`media` directory in `php` container:

![image](https://user-images.githubusercontent.com/19478137/208382386-4d6853b2-99c2-4299-877c-44cc43b6e1d2.png)

By the way, I think that if you install Sylius via Docker, the product images (generated by fixtures) will not be displayed on the website because of the permissions.

@nicolalazzaro has the same problem and he didn’t have this problem in the past, so I think the problem is not my setup.

**Steps to reproduce**  

1. Login to admin panel
2. Go to `Products > Media`
3. Upload a media

I tried with 1.12.0 version and same problem..  😕 

I use Docker Desktop 4.15.0 on MacOS Monterey.

**Possible Solution**  

?

**Comment by umpirsky** [comment]
```
/srv/sylius # ls -l public/media/cache/sylius_shop_product_thumbnail/
total 8
drwxrwx---    3 www-data www-data      4096 May 10 18:22 af
```

`chmod -R +x public/media/cache/` makes them work:

```
/srv/sylius # ls -l public/media/cache/sylius_shop_product_thumbnail/
total 8
drwxrwx--x    3 www-data www-data      4096 May 10 18:22 af
```

but as soon as you upload new image, it will not work.

**Comment by umpirsky** [comment]
Trying with:

```yaml
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    loaders:
        product_images:
            flysystem:
                filesystem_service: oneup_flysystem.product_images_filesystem
    data_loader: product_images

oneup_flysystem:
    adapters:
        product_images:
            local:
                location: "%kernel.project_dir%/public/media/image"
                permissions:
                    file:
                        public: 0777
                        private: 0777
                    dir:
                        public: 0777
                        private: 0777

    filesystems:
        product_images:
            adapter: product_images
```

But still no luck, it creates dirs without `x` on others...
